#!/bin/sh

set -e

VERSION=$(cat VERSION)
DOCKER_IMAGE=${DOCKER_IMAGE:-sameersbn/gitlab}

docker build -t $DOCKER_IMAGE .

docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest
docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$VERSION

docker push $DOCKER_IMAGE:latest
docker push $DOCKER_IMAGE:$VERSION
